services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    env_file:
      - ../docker/.env
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${HTTPS_PORT}:${HTTPS_PORT}
      - ${HTTP_PROXY_PORT}:${HTTP_PROXY_PORT}/udp
    volumes:
      - ../docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ../docker/caddy/certs:/etc/caddy/certs
      - ../docker/caddy/data:/data
      - ../docker/caddy/logs:/var/log/caddy
      - ../docker/caddy/public:/usr/share/caddy/html
    networks:
      - nexus

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    env_file:
      - ../docker/.env
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../docker/portainer/data:/data
      - ../docker/portainer/logs:/var/log/portainer
      - ../docker/portainer/certs:/certs
    ports:
      - ${PORTAINER_PORT}
      - ${PORTAINER_TCP_PORT}/tcp
    depends_on:
      - caddy
    networks:
      - nexus

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - ../docker/.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - ../docker/postgres/data:/var/lib/postgresql/data
      - ../docker/postgres/logs:/var/log/postgresql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - nexus

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file:
      - ../docker/.env
    ports:
      - ${PGADMIN_LISTEN_PORT}
    volumes:
      - ../docker/pgadmin/data:/var/lib/pgadmin
      - ../docker/pgadmin/logs:/var/log/pgadmin
    depends_on:
      - postgres
      - caddy
    networks:
      - nexus

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - ../docker/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ../docker/mongo/data:/data/db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - nexus
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: unless-stopped
    env_file:
      - ../docker/.env
    ports:
      - ${MONGO_EXPRESS_PORT}
    depends_on:
      - mongodb
      - caddy
    volumes:
      - ../docker/express/data:/data
    networks:
      - nexus

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    env_file:
      - ../docker/.env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ../docker/redis/data:/data
    networks:
      - nexus

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    env_file:
      - ../docker/.env
    ports:
      - ${REDIS_COMMANDER_PORT}
    environment:
      - PORT=${REDIS_COMMANDER_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
      - caddy
    volumes:
      - ../docker/commander/data:/data
    networks:
      - nexus

  minio:
    container_name: minio
    image: minio/minio:latest
    restart: unless-stopped
    env_file:
      - ../docker/.env
    ports:
      - ${MINIO_S3_PORT}:${MINIO_S3_PORT}
      - ${MINIO_CONSOLE_PORT}
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    volumes:
      - ../docker/minio/data:/data
      - ../docker/minio/logs:/var/log/minio
    depends_on:
      - caddy
    networks:
      - nexus

networks:
  nexus:
    driver: bridge

volumes:
  caddy:
  postgres:
  pgadmin:
  mongo:
  mongo-express:
  redis:
  redis-commander: