---
services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${HTTPS_PORT}:${HTTPS_PORT}
      - ${HTTP_PROXY_PORT}:${HTTP_PROXY_PORT}/udp
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/certs:/etc/caddy/certs
      - ./caddy/data:/data
      - ./caddy/logs:/var/log/caddy
      - ./caddy/public:/usr/share/caddy/html
    networks:
      - nexus

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    env_file:
      - .env
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
      - ./portainer/logs:/var/log/portainer
      - ./portainer/certs:/certs
    ports:
      - ${PORTAINER_PORT}
      - ${PORTAINER_TCP_PORT}/tcp
    depends_on:
      - caddy
    networks:
      - nexus

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/logs:/var/log/postgresql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - nexus

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PGADMIN_LISTEN_PORT}
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
      - ./pgadmin/logs:/var/log/pgadmin
    depends_on:
      - postgres
      - caddy
    networks:
      - nexus

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongo/data:/data/db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - nexus
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${MONGO_EXPRESS_PORT}
    depends_on:
      - mongodb
      - caddy
    volumes:
      - ./express/data:/data
    networks:
      - nexus

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./redis/data:/data
    networks:
      - nexus

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${REDIS_COMMANDER_PORT}
    environment:
      - PORT=${REDIS_COMMANDER_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
      - caddy
    volumes:
      - ./commander/data:/data
    networks:
      - nexus

  ftp:
    container_name: ftp
    image: stilliard/pure-ftpd:latest
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./ftp/data:/home/ftpusers
      - ./ftp/config:/etc/pure-ftpd/passwd
    environment:
      FTP_USER_NAME: "admin"
      FTP_USER_PASS: "Password123"
      FTP_USER_HOME: "/home/ftpusers/myuser"
      PUBLICHOST: "localhost"
    networks:
      - nexus

  n8n:
    container_name: n8n
    image: n8nio/n8n:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_TYPE=${N8N_DB_TYPE}
      - DB_POSTGRESDB_HOST=${N8N_DB_HOST}
      - DB_POSTGRESDB_PORT=${N8N_DB_PORT}
      - DB_POSTGRESDB_DATABASE=${N8N_DB}
      - DB_POSTGRESDB_USER=${N8N_DB_USER}
      - DB_POSTGRESDB_PASSWORD=${N8N_DB_PASSWORD}
    ports:
      - ${N8N_PORT}
    command: [ "start" ]
    links:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/flows:/files
      - ./n8n/logs:/var/log/n8n
    depends_on:
      - postgres
      - caddy
    networks:
      - nexus

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:s6
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${FILEBROWSER_PORT}
    environment:
      PGID: $(id -g)
      PUID: $(id -u)
    depends_on:
      - caddy
    volumes:
      - ./filebrowser/database:/database
      - ./filebrowser/srv:/srv
      - ./filebrowser/config:/config
    networks:
      - nexus

  stalwart:
    container_name: stalwart
    image: stalwartlabs/stalwart:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "995:995"
      - "110:110"
      - "4190:4190"
      - "993:993"
      - "143:143"
      - "465:465"
      - "587:587"
      - "25:25"
      - ${STALWART_PORT}
    volumes:
      - ./stalwart/data:/opt/stalwart/data
      - ./stalwart/logs:/opt/stalwart/logs
      - ./stalwart/config:/opt/stalwart/etc
    depends_on:
      - caddy
    networks:
      - nexus

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
    networks:
      - nexus

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.3-management
    restart: unless-stopped
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}
    env_file:
      - .env
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/logs:/var/log/rabbitmq
    networks:
      - nexus

  minio:
    container_name: minio
    image: minio/minio:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${MINIO_S3_PORT}:${MINIO_S3_PORT}
      - ${MINIO_CONSOLE_PORT}
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    volumes:
      - ./minio/data:/data
      - ./minio/logs:/var/log/minio
    depends_on:
      - caddy
    networks:
      - nexus

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${MAILHOG_PORT}:${MAILHOG_PORT}
      - ${MAILHOG_HTTP_PORT}
    volumes:
      - ./mail/dir:/maildir
      - ./mail/data:/data
    depends_on:
      - caddy
    networks:
      - nexus

  sftpgo:
    container_name: sftpgo
    image: drakkan/sftpgo:latest
    ports:
      - "2022:2022"   # SFTP
      - "2021:2021"   # FTP
      - "8080"   # Web UI / REST API
      - "9090:9090"   # WebDAV
    env_file:
      - .env
    volumes:
      - ./sftpgo/data:/srv/sftpgo:z
      - ./sftpgo/config:/var/lib/sftpgo:z
      - ./sftpgo/etc:/etc/sftpgo:z
    networks:
      - nexus

  it-tools:
    container_name: it-tools
    image: corentinth/it-tools:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${IT_TOOLS_PORT}
    volumes:
      - ./it-tools/data:/data
    networks:
      - nexus

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/${USER}/.docker/config.json:/config.json
    command: --interval 300
    networks:
      - nexus

networks:
  nexus:
    driver: bridge

volumes:
  caddy:
  postgres:
  pgadmin:
  mongo:
  mongo-express:
  redis:
  n8n:
  n8n_data:
  rabbitmq:
  redis-commander:
  minio:
  mail:
  sftpgo:
  sftpgo_data:

