---
services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${CADDY_HTTP_PORT}:${CADDY_HTTP_PORT}
      - ${CADDY_HTTPS_PORT}:${CADDY_HTTPS_PORT}
      - ${CADDY_HTTP_PROXY_PORT}:${CADDY_HTTP_PROXY_PORT}/udp
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/certs:/etc/caddy/certs
      - ./caddy/data:/data
      - ./caddy/logs:/var/log/caddy
      - ./caddy/public:/usr/share/caddy/html
    networks:
      - nexus

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/${USER}/.docker/config.json:/config.json
    command: --interval 300
    networks:
      - nexus

include:
  - ./databases/docker-compose.yaml
  - ./mail/docker-compose.yaml
  - ./media/docker-compose.yaml
  - ./queues/docker-compose.yaml
  - ./servers/docker-compose.yaml
  - ./tools/docker-compose.yaml

networks:
  nexus:
    name: nexus
    driver: bridge

volumes:
  caddy:

