services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${HTTPS_PORT}:${HTTPS_PORT}
      - ${HTTP_PROXY_PORT}:${HTTP_PROXY_PORT}/udp
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/certs:/etc/caddy/certs
      - ./caddy/data:/data
      - ./caddy/logs:/var/log/caddy
      - ./caddy/public:/usr/share/caddy/html
    networks:
      - wallet

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    env_file:
      - .env
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
      - ./portainer/logs:/var/log/portainer
      - ./portainer/certs:/certs
    ports:
      - ${PORTAINER_PORT}
      - ${PORTAINER_TCP_PORT}/tcp
    depends_on:
      - caddy
    networks:
      - wallet

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/logs:/var/log/postgresql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - wallet

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PGADMIN_LISTEN_PORT}
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
      - ./pgadmin/logs:/var/log/pgadmin
    depends_on:
      - postgres
      - caddy
    networks:
      - wallet

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongo/data:/data/db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - wallet
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${MONGO_EXPRESS_PORT}
    depends_on:
      - mongodb
      - caddy
    volumes:
      - ./express/data:/data
    networks:
      - wallet

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./redis/data:/data
    networks:
      - wallet

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${REDIS_COMMANDER_PORT}
    environment:
      - PORT=${REDIS_COMMANDER_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
      - caddy
    volumes:
      - ./commander/data:/data
    networks:
      - wallet

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/${USER}/.docker/config.json:/config.json
    command: --interval 300
    networks:
      - wallet

networks:
  wallet:
    driver: bridge

volumes:
  caddy:
  postgres:
  pgadmin:
  mongo:
  redis-commander: