---
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/logs:/var/log/postgresql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - nexus
      - database
    healthcheck:
      test: echo 'SELECT 1' | psql -h localhost -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1
      interval: 10s
      timeout: 10s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PGADMIN_LISTEN_PORT}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
#      PGADMIN_SERVER_JSON_FILE: /pgadmin4n4/servers.json
      PGADMIN_DISABLE_POSTFIX: "False"
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_ENABLE_SESSION_EXPIRY: "True"
#      PGADMIN_CONFIG_MAIL_SERVER: "smtp.resend.com"
#      PGADMIN_CONFIG_MAIL_PORT: "587"
#      PGADMIN_CONFIG_MAIL_USE_TLS: "True"
#      PGADMIN_CONFIG_MAIL_USE_SSL: "False"
#      PGADMIN_CONFIG_MAIL_USERNAME: "resend"
#      PGADMIN_CONFIG_MAIL_PASSWORD: ""
#      PGADMIN_CONFIG_MAIL_SENDER: ""
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
    depends_on:
      - postgres
      - caddy
    networks:
      - nexus
      - database
      - default
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${PGADMIN_LISTEN_PORT}/misc/ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
    networks:
      - nexus
      - database
    healthcheck:
      test: echo 'SELECT 1' | mysql -h localhost -P ${MYSQL_PORT} -u ${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1
      interval: 10s
      timeout: 10s
      retries: 5

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PHPMYADMIN_PORT}
    entrypoint: /bin/sh -c "apt-get update && apt-get install -y curl && exec /docker-entrypoint.sh apache2-foreground"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1024M
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
      - caddy
    volumes:
      - ./phpmyadmin/config:/etc/phpmyadmin/config.user.inc.php
      - ./phpmyadmin/sessions:/sessions
    networks:
      - nexus
      - database
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongo/data:/data/db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - nexus
      - database
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${MONGO_EXPRESS_PORT}
    entrypoint: /bin/sh -c "apk add --no-cache curl && exec node app"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_DATABASE: ${MONGO_INITDB_DATABASE}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_SITE_BASEURL: /
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_SITE_COOKIESECRET: ${MONGO_EXPRESS_COOKIESECRET}
      ME_CONFIG_SITE_SESSIONSECRET: ${MONGO_EXPRESS_SESSIONSECRET}
      ME_CONFIG_SITE_SSL_ENABLED: False
      ME_CONFIG_SITE_SSL_CRT_PATH: ${MONGO_EXPRESS_SSL_CERTIFICATE}
      ME_CONFIG_SITE_SSL_KEY_PATH: ${MONGO_EXPRESS_SSL_KEY}
      ME_CONFIG_SITE_SSL_REJECT_UNAUTHORIZED: ${MONGO_EXPRESS_SSL_REJECT_UNAUTHORIZED}
      ME_CONFIG_SITE_SSL_KEY_PASSPHRASE: ${MONGO_EXPRESS_SSL_KEY_PASSPHRASE}
    depends_on:
      - mongodb
      - caddy
    volumes:
      - ./express/data:/data
      - ./express/logs:/var/log/express
      - ./express/config:/config
      - ./express/ssl:/ssl
    networks:
      - nexus
      - database
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:8081 | grep -E '^(200|401)$' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - ${REDIS_COMMANDER_PORT}
    environment:
      PORT: ${REDIS_COMMANDER_PORT}
      HTTP_USER: ${REDIS_COMMANDER_USERNAME}
      HTTP_PASSWORD: ${REDIS_COMMANDER_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis
      - caddy
    volumes:
      - ./commander/data:/data
    networks:
      - nexus
      - database
    healthcheck:
      test: curl --fail -s http://localhost:${REDIS_COMMANDER_PORT} || exit 1
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis/data:/data
    networks:
      - nexus
      - database
    healthcheck:
      test: echo 'ping' | redis-cli -h localhost -p ${REDIS_PORT} || exit 1
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  postgres:
    name: postgres
    driver: local
  pgadmin:
    name: pgadmin
    driver: local
  mysql:
    name: mysql
    driver: local
  phpmyadmin:
    name: phpmyadmin
    driver: local
  mongo:
    name: mongo
    driver: local
  express:
    name: express
    driver: local
  commander:
    name: commander
    driver: local
  redis:
    name: redis
    driver: local

networks:
  database:
    name: database
    driver: bridge