---
services:
  stalwart:
    container_name: stalwart
    image: stalwartlabs/stalwart:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${STALWART_POP3S_PORT}:${STALWART_POP3S_PORT}
      - ${STALWART_POP3_PORT}:${STALWART_POP3_PORT}
      - ${STALWART_MANAGESIEVE_PORT}:${STALWART_MANAGESIEVE_PORT}
      - ${STALWART_IMAPS_PORT}:${STALWART_IMAPS_PORT}
      - ${STALWART_IMAP_PORT}:${STALWART_IMAP_PORT}
      - ${STALWART_SMTPS_PORT}:${STALWART_SMTPS_PORT}
      - ${STALWART_SUBMISSION_PORT}:${STALWART_SUBMISSION_PORT}
      - ${STALWART_SMTP_PORT}:${STALWART_SMTP_PORT}
      - ${STALWART_HTTP_PORT}
    volumes:
      - ./stalwart/data:/opt/stalwart/data
      - ./stalwart/logs:/opt/stalwart/logs
      - ./stalwart/config:/opt/stalwart/etc
    depends_on:
      - caddy
    networks:
      - nexus

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${MAILHOG_SMTP_PORT}:${MAILHOG_SMTP_PORT}
      - ${MAILHOG_HTTP_PORT}
    volumes:
      - ./mail/dir:/maildir
      - ./mail/data:/data
    depends_on:
      - caddy
    networks:
      - nexus

volumes:
  stalwart:
    name: stalwart
    driver: local
  mailhog:
    name: mailhog
    driver: local

networks:
  nexus:
    name: nexus
    external: true