---
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    env_file:
      - .env
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    ports:
      - ${PORTAINER_HTTPS_PORT}
      - ${PORTAINER_HTTP_PORT}
    depends_on:
      - caddy
    networks:
      - nexus
      - tools

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - ${MAILHOG_SMTP_PORT}:1025
      - ${MAILHOG_WEB_PORT}
    volumes:
      - ./mailhog/data:/maildir
      - ./mailhog/config:/config
      - ./mailhog/logs:/logs
    depends_on:
      - caddy
    networks:
      - nexus
      - tools

volumes:
  portainer:
    name: portainer
    external: true

networks:
  tools:
    name: tools
    driver: bridge
